name: Build OpenWrt

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
          pwd
          whoami
          ls -la
