name: Build OpenWrt

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build OpenWrt using diffconfig
        run: |
          ./scripts/feeds update -a && ./scripts/feeds install -a
          cp diffconfig .config
          make defconfig
          make download
          make -j2 V=s

      - name: Upload openwrt binary to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt-testbuild
          path: bin/targets/lantiq/xrx200/*-sysupgrade.bin
