name: Build OpenWrt

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build OpenWrt using diffconfig
        run: |
          ./scripts/feeds update -a && ./scripts/feeds install -a
          cp diffconfig .config
          make defconfig
          make download
          make -j2 V=s

      - name: Upload openwrt binary to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt-targets
          path: bin/targets/lantiq/xrx200/

      - name: Upload packages to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt-packages
          path: bin/packages/mips_24kc/

      - name: Create a repository structure and package it
        run: |
          mkdir -vp repo/
          cp -vR bin/* repo/
          tar -czf repo/openwrt-fritzbox-repo.tar.gz repo/*
          
      - name: Release the repo tarball
        uses: softprops/action-gh-release@v1
        with:
          tag_name: OpenWrt-Fritzbox
          files: repo/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
